name: Discord Commit Notification

on:
  push:
    branches:
      - main

jobs:
  notify:
    if: github.actor != 'github-actions[bot]' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - name: Get short SHA
        id: vars
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Send Discord Webhook
        env:
          WEBHOOK: ${{ secrets.GITHUB }}
        run: |
          curl -H "Content-Type: application/json" \
          -X POST \
          -d "{
            \"username\": \"GitHub\",
            \"avatar_url\": \"https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png\",
            \"embeds\": [{
              \"title\": \"[${{ github.repository }}:${{ github.ref_name }}] New commit\",
              \"url\": \"https://github.com/${{ github.repository }}/commit/${{ github.sha }}\",
              \"color\": 5814783,
              \"author\": {
                \"name\": \"${{ github.actor }}\",
                \"icon_url\": \"https://github.com/${{ github.actor }}.png\"
              },
              \"description\": \"\`${{ env.SHORT_SHA }}\` ${{ github.event.head_commit.message }}\",
              \"footer\": {
                \"text\": \"Click to view commit\"
              }
            }]
          }" \
          $WEBHOOK