name: Livery Update

on:
  push:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: pip install requests discord-webhook

      - name: Run script
        env:
          LIVERY_UPDATE_WEBHOOK: ${{ secrets.LIVERY_UPDATE_WEBHOOK }}
        run: python3 .webhook/livery_update.py

      - name: Update commit file
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .webhook/commit.txt
          git commit -m "Update commit.txt" || exit 0
          git push
